version: '3.3'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:8.3.3'
        container_name: elasticsearch
        volumes:
            - /tmp/esdata:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            - discovery.type=single-node
