version: '3.3'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:8.3.3'
        container_name: elasticsearch
        volumes:
            - /tmp/esdata:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            - discovery.type=single-node
services:
    all-in-one:
        image: 'jaegertracing/all-in-one:1.37'
        container_name: jaeger
        environment:
            - COLLECTOR_ZIPKIN_HOST_PORT=:9411
            - COLLECTOR_OTLP_ENABLED=true
            - SPAN_STORAGE_TYPE=elasticsearch
            - ES_SERVER_URLS=http://elasticsearch:9200
            - ES_USERNAME=elastic
            - LOG_LEVEL=debug
        ports:
            - '6831:6831/udp'
            - '6832:6832/udp'
            - '5778:5778'
            - '16686:16686'
            - '4317:4317'
            - '4318:4318'
            - '14250:14250'
            - '14268:14268'
            - '14269:14269'
            - '9411:9411'

# docker network create jeager-network
# docker run --name elasticsearch --network=jeager-network -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.12.1
# docker run -d --name jaeger \
#     -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
#     -e COLLECTOR_OTLP_ENABLED=true \
#     -e SPAN_STORAGE_TYPE=elasticsearch \
#     -e ES_SERVER_URLS=http://elasticsearch:9200 \
#     -e ES_USERNAME=elastic \
#     -e LOG_LEVEL=debug \
#     -p 6831:6831/udp \
#     -p 6832:6832/udp \
#     -p 5778:5778 \
#     -p 16686:16686 \
#     -p 4317:4317 \
#     -p 4318:4318 \
#     -p 14250:14250 \
#     -p 14268:14268 \
#     -p 14269:14269 \
#     -p 9411:9411 \
#     --network=jeager-network \
#     jaegertracing/all-in-one:1.37