# change <kafka0> <kafka1> <kafka2> <user> <password> variables before use
version: "3"
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8080:8080
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: c0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: <kafka0>:9096
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="<user>" password="<password>";'
      KAFKA_CLUSTERS_1_NAME: c1
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: <kafka1>:9096
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="<user>" password="<password>";'
      KAFKA_CLUSTERS_2_NAME: c2
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: <kafka2>:9096
      KAFKA_CLUSTERS_2_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_2_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_2_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="<user>" password="<password>";'
